name: run build.py

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: secrets
    steps:
    - name: trigger album
    - uses: rshop/trigger-workflow-action@v1
    - with:
        token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        repository: 'lfkdsk/album'
        workflowId: 66585106
